sonar.projectKey=mitchins_daily-kotoba
sonar.organization=mitchins

sonar.projectName=daily-kotoba

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
# Written by `pytest --cov-report=xml` in the CI job before the scan runs.
sonar.python.coverage.reportPaths=coverage.xml
